### ISSUE TITLE
Replacing the Winner name from X/O by the user Choosing that Variable who won. 

### ISSUE THREAD

**Issue by thegreywalker** [Stark-Corp/Projects_Repo#2]
In this codebase, there are two Players, they are:
Player 1 and Player 2 
, and at the beginning of the game whatever variable the Player 1 chooses it gets stored in Choice_dict dictionary and so is for the Player 2 and they are independent of choosing any variable at all, but the problem lies while declearing the winner, it Decleares  whether X has won or O has won but here the Variable name should be replaced by the Player who have choosen the variable that won the game.

**Comment by ghost** [comment]
[New Text Document.txt](https://github.com/Stark-Corp/Projects_Repo/files/5902327/New.Text.Document.txt)
Added The player name functionality but winner is not getting declared after the game is over.

**Comment by thegreywalker** [comment]
The Problem is Solved by Calling the Key from Value in the Dictionary, and then Checking if the variable which won is exactly same as to which the player is stored in dictionary and then the Player's name is announced.

To refer about how to Call a Key Using a Value form a Dictionary, refer to this link: 
https://www.geeksforgeeks.org/python-get-key-from-value-in-dictionary/
